var state=JSON.parse(localStorage.getItem("irap-battle")||"null")||{history:[]},battle=null,currentPlayer=0,round=1,totalScores=[0,0],roundScores=[0,0];
function $(s){return document.querySelector(s)}
function esc(s){return String(s).replace(/[&<>"]/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]})}
function save(){localStorage.setItem("irap-battle",JSON.stringify(state))}
function render(){var e=$("#historyList");if(!state.history.length){e.innerHTML='<div class="empty">Nenhuma batalha registrada ainda.</div>';return}e.innerHTML=state.history.slice(0,20).map(function(x){return '<div class="history-item"><div><strong>'+esc(x.a)+'</strong><br>'+x.sa+' pontos</div><b>VS</b><div><strong>'+esc(x.b)+'</strong><br>'+x.sb+' pontos</div></div>'}).join("")}
function update(){var n=currentPlayer?battle.b:battle.a;$("#name1").textContent=battle.a;$("#name2").textContent=battle.b;$("#score1").textContent=totalScores[0];$("#score2").textContent=totalScores[1];$("#roundNow").textContent=round;$("#roundTotal").textContent="/ "+battle.total;$("#heroRound").textContent="ROUND "+round;$("#turnLabel").textContent="Vez de "+n;$("#meter").style.width=currentPlayer?"100%":"50%";$("#roundLog").textContent=roundScores[0]||roundScores[1]?"Round: "+roundScores[0]+" × "+roundScores[1]+" · Total: "+totalScores[0]+" × "+totalScores[1]:"Escolha uma nota."}
$("#startBtn").onclick=function(){battle={a:$("#mc1").value.trim()||"MC A",b:$("#mc2").value.trim()||"MC B",total:+$("#rounds").value};round=1;currentPlayer=0;totalScores=[0,0];roundScores=[0,0];$("#setup").classList.add("hidden");$("#arena").classList.remove("hidden");update()};
document.querySelectorAll(".judges button").forEach(function(b){b.onclick=function(){var v=+b.dataset.val;totalScores[currentPlayer]+=v;roundScores[currentPlayer]+=v;currentPlayer=1-currentPlayer;update()}});
$("#nextBtn").onclick=function(){if(!roundScores[0]&&!roundScores[1])return;if(round<battle.total){round++;currentPlayer=0;roundScores=[0,0];update()}else{state.history.unshift({a:battle.a,b:battle.b,sa:totalScores[0],sb:totalScores[1],rounds:battle.total,date:new Date().toLocaleDateString("pt-BR")});save();render();alert("Batalha registrada!");$("#arena").classList.add("hidden");$("#setup").classList.remove("hidden")}};
$("#resetBtn").onclick=function(){$("#arena").classList.add("hidden");$("#setup").classList.remove("hidden")};
$("#clearHistory").onclick=function(){if(confirm("Apagar todo o histórico?")){state.history=[];save();render()}};
render();