import React,{useEffect,useState}from"react";
import{Alert,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";

const KEY="irap-state-v1",BG="#09090B",CARD="#121216",LINE="#27272A",MUTED="#A1A1AA",LIME="#D7FF3F";
const fresh=()=>({a:"MC A",b:"MC B",rounds:4,round:1,turn:0,total:[0,0],current:[0,0],active:false});

export default function App(){
 const[b,setB]=useState(fresh()),[history,setHistory]=useState([]),[a,setA]=useState("MC A"),[c,setC]=useState("MC B"),[rounds,setRounds]=useState(4);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>{if(x)try{setHistory(JSON.parse(x).history||[])}catch{}})},[]);
 const save=async h=>{setHistory(h);await AsyncStorage.setItem(KEY,JSON.stringify({history:h}))};
 const start=()=>setB({a:a.trim()||"MC A",b:c.trim()||"MC B",rounds,round:1,turn:0,total:[0,0],current:[0,0],active:true});
 const point=v=>setB(x=>{const t=[...x.total],r=[...x.current];t[x.turn]+=v;r[x.turn]+=v;return{...x,total:t,current:r,turn:x.turn?0:1}});
 const finish=()=>{if(!b.current[0]&&!b.current[1])return Alert.alert("Round vazio","Registre uma pontuação antes de finalizar.");if(b.round<b.rounds)return setB(x=>({...x,round:x.round+1,turn:0,current:[0,0]}));const item={id:Date.now(),a:b.a,b:b.b,sa:b.total[0],sb:b.total[1],rounds:b.rounds,date:new Date().toLocaleDateString("pt-BR")};save([item,...history].slice(0,50));Alert.alert("Batalha registrada!",item.sa===item.sb?"Empate!":item.sa>item.sb?item.a+" venceu!":item.b+" venceu!");setB(fresh())};
 const clear=()=>Alert.alert("Apagar histórico","Remover todas as batalhas?",[{text:"Cancelar",style:"cancel"},{text:"Apagar",style:"destructive",onPress:()=>save([])}]);
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.wrap}>
  <Text style={s.brand}>iRap</Text><Text style={s.eyebrow}>CHAMADO DO RAP</Text><Text style={s.hero}>Seu palco.{"\n"}<Text style={s.lime}>Sua rima.</Text> Seu legado.</Text><Text style={s.muted}>A arena mobile para organizar, pontuar e guardar cada duelo.</Text>
  {!b.active?<View style={s.card}><Text style={s.title}>Nova batalha</Text><Text style={s.label}>MC 1</Text><TextInput value={a} onChangeText={setA} style={s.input} placeholder="Nome do MC" placeholderTextColor="#666"/><Text style={s.label}>MC 2</Text><TextInput value={c} onChangeText={setC} style={s.input} placeholder="Nome do MC" placeholderTextColor="#666"/><Text style={s.label}>Rounds</Text><View style={s.row}>{[3,4,5].map(n=><TouchableOpacity key={n} onPress={()=>setRounds(n)} style={[s.choice,rounds===n&&s.activeChoice]}><Text style={s.choiceText}>{n}</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.primary} onPress={start}><Text style={s.primaryText}>ENTRAR NA ARENA →</Text></TouchableOpacity></View>
  :<View style={s.card}><Text style={s.eyebrow}>ROUND {b.round} / {b.rounds}</Text><View style={s.scoreRow}><View style={s.player}><Text style={s.name}>{b.a}</Text><Text style={s.score}>{b.total[0]}</Text></View><Text style={s.vs}>VS</Text><View style={s.player}><Text style={s.name}>{b.b}</Text><Text style={s.score}>{b.total[1]}</Text></View></View><Text style={s.turn}>Vez de {b.turn?b.b:b.a}</Text><Text style={s.roundScore}>Round: {b.current[0]} × {b.current[1]}</Text>{["Flow","Rima","Impacto"].map(cat=><View key={cat} style={s.judge}><Text style={s.judgeTitle}>{cat}</Text><View style={s.row}>{[1,2,3].map(v=><TouchableOpacity key={v} style={s.point} onPress={()=>point(v)}><Text style={s.pointText}>+{v}</Text></TouchableOpacity>)}</View></View>)}<TouchableOpacity style={s.primary} onPress={finish}><Text style={s.primaryText}>{b.round<b.rounds?"FINALIZAR ROUND →":"ENCERRAR BATALHA →"}</Text></TouchableOpacity></View>}
  <View style={s.card}><View style={s.historyHead}><Text style={s.title}>Últimas batalhas</Text><TouchableOpacity onPress={clear}><Text style={s.delete}>Apagar</Text></TouchableOpacity></View>{history.length?history.slice(0,10).map(x=><View key={x.id} style={s.hist}><Text style={s.histName}>{x.a}</Text><Text style={s.histScore}>{x.sa} × {x.sb}</Text><Text style={s.histName}>{x.b}</Text><Text style={s.date}>{x.date}</Text></View>):<Text style={s.muted}>Nenhuma batalha registrada ainda.</Text>}</View>
  <View style={s.about}><Text style={s.eyebrow}>iRAP</Text><Text style={s.title}>Feito para quem vive a cultura.</Text><Text style={s.muted}>Android + iOS com histórico local.</Text></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BG},wrap:{padding:22,paddingBottom:50},brand:{fontSize:30,fontWeight:"900",color:LIME,marginBottom:22},eyebrow:{fontSize:11,fontWeight:"900",letterSpacing:2,color:LIME},hero:{fontSize:42,lineHeight:43,fontWeight:"900",color:"#F5F5F5",marginTop:10,marginBottom:14},lime:{color:LIME},muted:{color:MUTED,fontSize:15,lineHeight:22},card:{backgroundColor:CARD,borderWidth:1,borderColor:LINE,borderRadius:20,padding:20,marginTop:22},title:{fontSize:25,fontWeight:"900",color:"#F5F5F5",marginBottom:18},label:{color:MUTED,fontSize:12,fontWeight:"800",marginTop:10},input:{backgroundColor:"#1A1A1F",borderWidth:1,borderColor:LINE,borderRadius:11,color:"#FFF",padding:14,marginTop:6},row:{flexDirection:"row",gap:10,marginTop:8},choice:{flex:1,borderWidth:1,borderColor:LINE,borderRadius:10,padding:13,alignItems:"center"},activeChoice:{backgroundColor:LIME,borderColor:LIME},choiceText:{color:"#FFF",fontWeight:"900"},primary:{backgroundColor:LIME,borderRadius:12,padding:16,alignItems:"center",marginTop:20},primaryText:{color:"#111",fontWeight:"900"},scoreRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginVertical:22},player:{flex:1,alignItems:"center"},name:{color:MUTED,fontWeight:"800",textAlign:"center"},score:{color:"#FFF",fontSize:48,fontWeight:"900"},vs:{color:LIME,fontWeight:"900",marginHorizontal:8},turn:{color:LIME,fontSize:18,fontWeight:"900",textAlign:"center"},roundScore:{color:MUTED,textAlign:"center",marginTop:5},judge:{borderTopWidth:1,borderTopColor:LINE,paddingTop:15,marginTop:12},judgeTitle:{color:"#FFF",fontWeight:"900",fontSize:17},point:{flex:1,backgroundColor:"#1C1C21",borderWidth:1,borderColor:LINE,borderRadius:9,padding:12,alignItems:"center"},pointText:{color:"#FFF",fontWeight:"900"},historyHead:{flexDirection:"row",justifyContent:"space-between"},delete:{color:"#FF6B6B",fontWeight:"800"},hist:{flexDirection:"row",alignItems:"center",borderTopWidth:1,borderTopColor:LINE,paddingVertical:15,gap:8},histName:{color:"#FFF",fontWeight:"800",flex:1},histScore:{color:LIME,fontWeight:"900"},date:{color:"#666",fontSize:9},about:{paddingVertical:35,alignItems:"center",gap:10}});
